{
 "title": "HMAC File Server Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "HMAC Dashboard",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h3 style=\"color:#4CAF50; font-family: 'Arial', sans-serif; font-weight: bold;\">\n    HMAC Dashboard\n</h3>\n<p style=\"font-family: 'Verdana', sans-serif; color:#333;\">\n    This dashboard monitors <strong style=\"color:#FF5733;\">key metrics</strong> for the <span style=\"font-style:italic; color:#007BFF;\">HMAC File Server</span>.\n</p>"
   }
  },
  {
   "title": "HMAC GO Threads",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "threads" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_threads", "legendFormat": "{{hmax-file-server}}" }
   ]
  },
  {
   "title": "HMAC Upload(s)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hmac_file_server_uploads_total", "legendFormat": "{{hmax-file-server}}" }
   ]
  },
  {
   "title": "HMAC Upload Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hmac_file_server_upload_errors_total",
     "legendFormat": "Upload Errors"
    }
   ]
  },
  {
   "title": "Received Network Bytes",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_network_receive_bytes_total",
     "legendFormat": "Received Network Bytes"
    }
   ]
  },
  {
   "title": "Transmitted Network Bytes",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_network_transmit_bytes_total",
     "legendFormat": "Transmitted Network Bytes"
    }
   ]
  },
  {
   "title": "HMAC Upload Duration",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hmac_file_server_upload_duration_seconds_bucket",
     "legendFormat": "Upload Duration"
    }
   ]
  },
  {
   "title": "Process Virtual Memory Usage",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "Virtual Memory" }
   ]
  },
  {
   "title": "Process Resident Memory Usage",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "Resident Memory" }
   ]
  },
  {
   "title": "Total CPU Time",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "seconds" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "Total CPU Time" }
   ]
  }
 ]
}