{
 "title": "HMAC File Server Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "HMAC Dashboard",
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align: center; background-color: transparent; padding: 20px;\">\n    <h3 style=\"color: white; font-family: 'Arial', sans-serif; font-weight: bold;\">HMAC Dashboard</h3>\n    <img src=\"https://block.uuxo.net/hmac_icon.png\" alt=\"HMAC Icon\" style=\"width: 50px; height: 50px; display: block; margin: 10px auto;\">\n    <p style=\"font-family: 'Verdana', sans-serif; color: white;\">\n        This dashboard monitors <strong style=\"color: #FF5733;\">key metrics</strong> for the \n        <span style=\"font-style: italic; color: #007BFF;\">HMAC File Server</span>.\n    </p>\n</div>\n"
   }
  },
  {
   "title": "HMAC CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hmac_cpu_usage_percent", "legendFormat": "Downloads" }
   ]
  },
  {
   "title": "HMAC Memory Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hmac_memory_usage_bytes", "legendFormat": "Download Errors" }
   ]
  },
  {
   "title": "HMAC GoRoutines",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hmac_goroutines_count", "legendFormat": "Download Errors" }
   ]
  },
  {
   "title": "HMAC Uploads",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hmac_file_server_uploads_total", "legendFormat": "Uploads" }
   ]
  },
  {
   "title": "HMAC Downloads",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hmac_file_server_downloads_total",
     "legendFormat": "Downloads"
    }
   ]
  },
  {
   "title": "HMAC GO Threads",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_threads", "legendFormat": "{{hmac-file-server}}" }
   ]
  },
  {
   "title": "HMAC Active Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hmac_active_connections_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HMAC infected file(s)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hmac_infected_files_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HMAC Upload Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hmac_file_server_upload_errors_total",
     "legendFormat": "Upload Errors"
    }
   ]
  },
  {
   "title": "HMAC Download Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hmac_file_server_download_errors_total",
     "legendFormat": "Download Errors"
    }
   ]
  },
  {
   "title": "Thumbnails Processed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hmac_thumbnails_processed_total",
     "legendFormat": "Upload Errors"
    }
   ]
  },
  {
   "title": "Thumbnails Processed Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hmac_thumbnail_processing_errors_total",
     "legendFormat": "Upload Errors"
    }
   ]
  },
  {
   "title": "Thumbnails Process Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hmac_thumbnail_processing_time_seconds_count",
     "legendFormat": "Upload Errors"
    }
   ]
  },
  {
   "title": "HMAC Up/Down Duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hmac_file_server_upload_duration_seconds_sum + hmac_file_server_download_duration_seconds_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HMAC Cache Misses",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hmac_cache_misses_total", "legendFormat": "{{hmac-file-server}}" }
   ]
  },
  {
   "title": "HMAC FileTTL Deletion(s)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hm", "legendFormat": "__auto" }
   ]
  }
 ]
}