{
 "title": "HMAC File Server Metrics",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "HMAC Dashboard",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h3 style=\"color:white; font-family: 'Arial', sans-serif; font-weight: bold;\">HMAC Dashboard</h3>\n<p style=\"font-family: 'Verdana', sans-serif; color:white;\">This dashboard monitors <strong style=\"color:#FF5733;\">key metrics</strong> for the <span style=\"font-style:italic; color:#007BFF;\">HMAC File Server</span>.</p>\n"
   }
  },
  {
   "title": "HMAC GO Threads",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "threads" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_threads", "legendFormat": "{{hmac-file-server}}" }
   ]
  },
  {
   "title": "HMAC Disk Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hmac_disk_usage_bytes", "legendFormat": "Download Errors" }
   ]
  },
  {
   "title": "HMAC Memory Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hmac_memory_usage_bytes", "legendFormat": "Download Errors" }
   ]
  },
  {
   "title": "HMAC infected file(s)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "count" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hmac_infected_files_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HMAC Up/Down Bucket",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "connetions" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hmac_active_connections_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HMAC CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hmac_cpu_usage_percent", "legendFormat": "Downloads" }
   ]
  },
  {
   "title": "HMAC Uploads",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hmac_file_server_uploads_total", "legendFormat": "Uploads" }
   ]
  },
  {
   "title": "HMAC Downloads",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hmac_file_server_downloads_total",
     "legendFormat": "Downloads"
    }
   ]
  },
  {
   "title": "HMAC Up/Down Bucket",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expr": "sum(hmac_file_server_upload_duration_seconds_bucket{job=\"hmac-file-server\"}) + sum(hmac_file_server_download_duration_seconds_bucket{job=\"hmac-file-server\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HMAC Upload Errors",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hmac_file_server_upload_errors_total",
     "legendFormat": "Upload Errors"
    }
   ]
  },
  {
   "title": "HMAC Download Errors",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hmac_file_server_download_errors_total",
     "legendFormat": "Download Errors"
    }
   ]
  }
 ]
}